In [843]:
# import dependencies
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [844]:
mydata_load = "./Resources/nhes_19_pfi_cleaned.csv"
school_data_df = pd.read_csv(mydata_load)
school_data_df = pd.DataFrame(school_data_df)

In [845]:
#school_data_df.head(5)
list(school_data_df.columns)
#school_data_df.head(5)

['Unnamed: 0',
 'ALLGRADEX_2',
 'ALLGRADEX_3',
 'ALLGRADEX_4',
 'ALLGRADEX_5',
 'ALLGRADEX_6',
 'ALLGRADEX_7',
 'ALLGRADEX_8',
 'ALLGRADEX_9',
 'ALLGRADEX_10',
 'ALLGRADEX_11',
 'ALLGRADEX_12',
 'ALLGRADEX_13',
 'ALLGRADEX_14',
 'ALLGRADEX_15',
 'SEGRADES_0',
 'SEGRADES_1',
 'CENREG_1',
 'CENREG_2',
 'CENREG_3',
 'CENREG_4',
 'EDCPUB_1',
 'EDCPUB_2',
 'EDCCAT_1',
 'EDCCAT_2',
 'EDCREL_1',
 'EDCREL_2',
 'EDCPRI_1',
 'EDCPRI_2',
 'EDCINTK12_1',
 'EDCINTK12_2',
 'EDCHSFL_1',
 'EDCHSFL_2',
 'DISTASSI_1',
 'DISTASSI_2',
 'SCHRTSCHL_1',
 'SCHRTSCHL_2',
 'SCHLMAGNET_1',
 'SCHLMAGNET_2',
 'SEENJOY_1',
 'SEENJOY_2',
 'SEENJOY_3',
 'SEENJOY_4',
 'SEABSNT_1',
 'SEABSNT_2',
 'SEABSNT_3',
 'SEABSNT_4',
 'FCSCHOOL_1',
 'FCSCHOOL_2',
 'FCSCHOOL_3',
 'FCSCHOOL_4',
 'FCTEACHR_1',
 'FCTEACHR_2',
 'FCTEACHR_3',
 'FCTEACHR_4',
 'FCSTDS_1',
 'FCSTDS_2',
 'FCSTDS_3',
 'FCSTDS_4',
 'FHHOME_1',
 'FHHOME_2',
 'FHHOME_3',
 'FHHOME_4',
 'FHWKHRS_3',
 'FOSTORY2X_1',
 'FOSTORY2X_2',
 'FOCRAFTS_1',
 'FOCRAFTS_2',
 'FOGAMES_1',
 'FOGAMES_2',
 'FOBUILDX_1',
 'FOBUILDX_2',
 'FOSPORT_1',
 'FOSPORT_2',
 'FORESPON_1',
 'FORESPON_2',
 'FOHISTX_1',
 'FOHISTX_2',
 'FODINNERX_0',
 'FODINNERX_1',
 'FODINNERX_2',
 'FODINNERX_3',
 'FODINNERX_4',
 'FODINNERX_5',
 'FODINNERX_6',
 'FODINNERX_7',
 'FOLIBRAYX_1',
 'FOLIBRAYX_2',
 'FOBOOKSTX_1',
 'FOBOOKSTX_2',
 'FOCONCRTX_1',
 'FOCONCRTX_2',
 'FOMUSEUMX_1',
 'FOMUSEUMX_2',
 'FOZOOX_1',
 'FOZOOX_2',
 'FOGROUPX_1',
 'FOGROUPX_2',
 'HHENGLISH_1',
 'HHENGLISH_2',
 'CSPEAKX_1',
 'CSPEAKX_2',
 'CSPEAKX_3',
 'CSPEAKX_4',
 'CSPEAKX_5',
 'CSPEAKX_6',
 'HHTOTALXX_2',
 'HHTOTALXX_3',
 'HHTOTALXX_4',
 'HHTOTALXX_5',
 'HHTOTALXX_6',
 'HHTOTALXX_7',
 'HHTOTALXX_8',
 'HHTOTALXX_9',
 'HHTOTALXX_10',
 'HHPRTNRSX_0',
 'HHPRTNRSX_1',
 'HHPRTNRSX_2',
 'P1REL_1',
 'P1REL_2',
 'P1REL_3',
 'P1REL_4',
 'P1REL_5',
 'P1REL_6',
 'P1SEX_1',
 'P1SEX_2',
 'P1AGE_1',
 'P1AGE_2',
 'P1AGE_3',
 'P1AGE_4',
 'P1AGE_5',
 'P2AGE_1',
 'P2AGE_2',
 'P2AGE_3',
 'P2AGE_4',
 'P2AGE_5',
 'P2REL_1',
 'P2REL_2',
 'P2REL_3',
 'P2REL_4',
 'P2REL_5',
 'P2REL_6',
 'P2SEX_1',
 'P2SEX_2',
 'P2MRSTA_1',
 'P2MRSTA_2',
 'P2MRSTA_3',
 'P2MRSTA_4',
 'P2MRSTA_5',
 'PAR1EMPL_1',
 'PAR1EMPL_2',
 'PAR1EMPL_3',
 'PAR1EMPL_4',
 'PAR1FTFY_1',
 'PAR1FTFY_2',
 'PAR1FTFY_3',
 'PAR2FTFY_1',
 'PAR2FTFY_2',
 'PAR2FTFY_3',
 'NUMSIBSX_0',
 'NUMSIBSX_1',
 'NUMSIBSX_2',
 'NUMSIBSX_3',
 'NUMSIBSX_4',
 'NUMSIBSX_5',
 'NUMSIBSX_6',
 'NUMSIBSX_7',
 'TTLHHINC_1',
 'TTLHHINC_2',
 'TTLHHINC_3',
 'TTLHHINC_4',
 'TTLHHINC_5',
 'TTLHHINC_6',
 'TTLHHINC_7',
 'TTLHHINC_8',
 'TTLHHINC_9',
 'TTLHHINC_10',
 'TTLHHINC_11',
 'TTLHHINC_12',
 'OWNRNTHB_1',
 'OWNRNTHB_2',
 'OWNRNTHB_3',
 'HVINTSPHO_1',
 'HVINTSPHO_2',
 'HVINTCOM_1',
 'HVINTCOM_2',
 'INTACC_1',
 'INTACC_2',
 'INTACC_3',
 'INTACC_4',
 'CHLDNT_1',
 'CHLDNT_2',
 'CHLDNT_3',
 'CHLDNT_4',
 'LRNCOMP_1',
 'LRNCOMP_2',
 'LRNTAB_1',
 'LRNTAB_2',
 'LRNCELL_1',
 'LRNCELL_2']

In [846]:
#Creating a correlation matrix
school_data_df.corr()

,Unnamed: 0,ALLGRADEX_2,ALLGRADEX_3,ALLGRADEX_4,ALLGRADEX_5,ALLGRADEX_6,ALLGRADEX_7,ALLGRADEX_8,ALLGRADEX_9,ALLGRADEX_10,...,CHLDNT_1,CHLDNT_2,CHLDNT_3,CHLDNT_4,LRNCOMP_1,LRNCOMP_2,LRNTAB_1,LRNTAB_2,LRNCELL_1,LRNCELL_2
Unnamed: 0,1.000000,-0.004912,0.014405,0.002421,-0.004935,0.016563,-0.008261,0.022519,-0.017663,-0.007524,...,-0.013632,0.026594,-0.026862,0.008036,-0.000466,0.000466,0.000165,-0.000165,-0.008124,0.008124
ALLGRADEX_2,-0.004912,1.000000,-0.006402,-0.032678,-0.034512,-0.038738,-0.041822,-0.043716,-0.048887,-0.050667,...,-0.068595,0.042823,0.060310,-0.012201,-0.126457,0.126457,0.076277,-0.076277,-0.078834,0.078834
ALLGRADEX_3,0.014405,-0.006402,1.000000,-0.007956,-0.008403,-0.009432,-0.010183,-0.010644,-0.011903,-0.012336,...,-0.029338,0.011517,0.038295,-0.004582,-0.033743,0.033743,0.015063,-0.015063,-0.015423,0.015423
ALLGRADEX_4,0.002421,-0.032678,-0.007956,1.000000,-0.042893,-0.048145,-0.051977,-0.054332,-0.060759,-0.062970,...,-0.108477,0.071380,0.068013,0.025200,-0.152580,0.152580,0.092211,-0.092211,-0.098630,0.098630
ALLGRADEX_5,-0.004935,-0.034512,-0.008403,-0.042893,1.000000,-0.050848,-0.054895,-0.057382,-0.064170,-0.066505,...,-0.084530,0.054461,0.051958,0.026646,-0.095328,0.095328,0.103295,-0.103295,-0.119507,0.119507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LRNCOMP_2,0.000466,0.126457,0.033743,0.152580,0.095328,0.051115,0.050869,0.013389,0.001417,-0.029208,...,-0.118696,0.082591,0.057356,0.046304,-1.000000,1.000000,0.122631,-0.122631,-0.111387,0.111387
LRNTAB_1,0.000165,0.076277,0.015063,0.092211,0.103295,0.095523,0.089603,0.080283,0.018992,-0.020179,...,0.019360,-0.011814,-0.004746,-0.024347,-0.122631,0.122631,1.000000,-1.000000,-0.022079,0.022079
LRNTAB_2,-0.000165,-0.076277,-0.015063,-0.092211,-0.103295,-0.095523,-0.089603,-0.080283,-0.018992,0.020179,...,-0.019360,0.011814,0.004746,0.024347,0.122631,-0.122631,-1.000000,1.000000,0.022079,-0.022079
LRNCELL_1,-0.008124,-0.078834,-0.015423,-0.098630,-0.119507,-0.147114,-0.152877,-0.098744,-0.042718,0.009202,...,0.210928,-0.166484,-0.093787,-0.019327,0.111387,-0.111387,-0.022079,0.022079,1.000000,-1.000000
LRNCELL_2,0.008124,0.078834,0.015423,0.098630,0.119507,0.147114,0.152877,0.098744,0.042718,-0.009202,...,-0.210928,0.166484,0.093787,0.019327,-0.111387,0.111387,0.022079,-0.022079,-1.000000,1.000000

In [847]:
X = school_data_df.drop(columns = {'SEGRADES_0', 'Unnamed: 0','SEGRADES_1', 'ALLGRADEX_2', 'ALLGRADEX_3', 'ALLGRADEX_4', 'ALLGRADEX_5', 'ALLGRADEX_6', 'ALLGRADEX_7', 'ALLGRADEX_8', 'ALLGRADEX_9', 'ALLGRADEX_10', 'ALLGRADEX_11', 'ALLGRADEX_12', 'ALLGRADEX_13', 'ALLGRADEX_14', 'ALLGRADEX_15'}, axis=1)
y = school_data_df['SEGRADES_1']

In [848]:


#Setting the value for X and Y
#X = school_data_df[['SEENJOY_1','FCSCHOOL_1','FCTEACHR_1','FCSTDS_1','P2REL_1','SEABSNT_1','FHHOME_4','P1REL_1','TTLHHINC_12','FOBOOKSTX_1','P2MRSTA_1','OWNRNTHB_1','FOLIBRAYX_1','FOCONCRTX_1','FOGAMES_1','FOMUSEUMX_1','HVINTCOM_1','FOSPORT_1','TTLHHINC_11','INTACC_1','LRNCOMP_1','P1SEX_1','FOGROUPX_1','FOSTORY2X_1','P2SEX_2','LRNTAB_1','TTLHHINC_10','HHTOTALXX_4','P2AGE_3','CHLDNT_1','PAR1EMPL_1','FOCRAFTS_1',
#'P1AGE_3',
#'NUMSIBSX_1',
#'PAR1FTFY_1',
#'TTLHHINC_9',
#'HHENGLISH_1',
#'CSPEAKX_2',
#'CSPEAKX_6',
#'PAR2FTFY_1',
#'HHPRTNRSX_0',
#'EDCINTK12_2',
#'EDCPUB_1',
#'EDCHSFL_2',
#'FORESPON_2',
#'FODINNERX_7',
#'DISTASSI_2',
#'SCHLMAGNET_1',
#'FODINNERX_6',
#'HVINTSPHO_1',
#'CENREG_2',
#'FOBUILDX_1',
#'SCHRTSCHL_2',
#'FOHISTX_2',
#'EDCREL_2',
#'NUMSIBSX_7',
#'LRNCELL_2',
#'FOZOOX_1',
#'P2AGE_1',
#'CENREG_3',
#'EDCCAT_2',
#'CENREG_1',
#'PAR1EMPL_2',
#'HHTOTALXX_5',
#'NUMSIBSX_2',
#'CSPEAKX_5',
#'EDCPRI_1'
#]]

In [850]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=.6, random_state=78)

In [851]:
# Creating a StandardScaler instance.
#scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
#X_scaler = scaler.fit(X_train)

# Scaling the data.
#X_train_scaled = X_scaler.transform(X_train)
#X_test_scaled = X_scaler.transform(X_test)

In [852]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [853]:
# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

In [854]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)

In [855]:
# Calculating the confusion matrix.
#we analyze how well our random forest model classifies loan applications
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0          620          717
Actual 1          355         1650

In [856]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [857]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0          620          717
Actual 1          355         1650

Accuracy Score : 0.6792339916217833
Classification Report
              precision    recall  f1-score   support

           0       0.64      0.46      0.54      1337
           1       0.70      0.82      0.75      2005

    accuracy                           0.68      3342
   macro avg       0.67      0.64      0.65      3342
weighted avg       0.67      0.68      0.67      3342

In [858]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.02848795615215745, 'SEENJOY_1'),
 (0.014061763421837977, 'FHHOME_4'),
 (0.013406745446346874, 'FCSCHOOL_1'),
 (0.013252112542813, 'SEENJOY_3'),
 (0.012348627294101163, 'FCTEACHR_1'),
 (0.012323612868866182, 'SEENJOY_2'),
 (0.011376790350240988, 'P2REL_1'),
 (0.011019538668347154, 'SEABSNT_1'),
 (0.010249704594519175, 'FHHOME_3'),
 (0.010220023779438366, 'FOSTORY2X_2'),
 (0.010219201851086742, 'LRNTAB_1'),
 (0.010141458003873796, 'CENREG_2'),
 (0.01004323169141481, 'CHLDNT_1'),
 (0.009921668552709307, 'CENREG_4'),
 (0.009812207653134026, 'FOGROUPX_2'),
 (0.009781276935549525, 'FODINNERX_7'),
 (0.009731162906882423, 'FOHISTX_1'),
 (0.009694704389070724, 'FOBUILDX_2'),
 (0.009688682605844936, 'FOHISTX_2'),
 (0.009662428890155067, 'HHTOTALXX_4'),
 (0.009560328249890513, 'LRNTAB_2'),
 (0.009465225885334437, 'FOSTORY2X_1'),
 (0.009464948670780243, 'CHLDNT_2'),
 (0.00945947169948182, 'FOBUILDX_1'),
 (0.009439355398606237, 'FOBOOKSTX_1'),
 (0.00942565084091429, 'FOGROUPX_1'),
 (0.009394769331555745, 'NUMSIBSX_1'),
 (0.009349948388963282, 'FOGAMES_1'),
 (0.009341276005393518, 'FOSPORT_2'),
 (0.009336462976485781, 'PAR2FTFY_1'),
 (0.009325101197971, 'FOGAMES_2'),
 (0.009295545077830859, 'FOSPORT_1'),
 (0.009278927300572445, 'FCTEACHR_2'),
 (0.009278347843842554, 'TTLHHINC_9'),
 (0.009147193115407966, 'FHHOME_2'),
 (0.009143527395164035, 'FORESPON_1'),
 (0.00910755250771146, 'LRNCELL_1'),
 (0.009097864655719816, 'FOCONCRTX_2'),
 (0.009095383669481288, 'FOLIBRAYX_1'),
 (0.009094867297871293, 'FODINNERX_5'),
 (0.009070231471721495, 'FORESPON_2'),
 (0.009051834727790583, 'CENREG_3'),
 (0.008914019726201754, 'FCSCHOOL_2'),
 (0.008856046060460941, 'FOBOOKSTX_2'),
 (0.008842079478700728, 'FOCONCRTX_1'),
 (0.008742179505755985, 'FOCRAFTS_2'),
 (0.008711328528815272, 'LRNCELL_2'),
 (0.008688585589729592, 'FCSTDS_1'),
 (0.008651400737221013, 'NUMSIBSX_0'),
 (0.008620071755863904, 'P2AGE_3'),
 (0.008562587668480576, 'FCSTDS_2'),
 (0.00845906845443915, 'FOCRAFTS_1'),
 (0.008366334231922587, 'TTLHHINC_8'),
 (0.008271232849744717, 'FOLIBRAYX_2'),
 (0.008175169043666873, 'P1REL_1'),
 (0.008150488572749135, 'CENREG_1'),
 (0.008090906182042877, 'PAR2FTFY_2'),
 (0.007986561835272049, 'PAR1FTFY_1'),
 (0.007896243976272255, 'HHTOTALXX_5'),
 (0.007873907681386566, 'PAR1FTFY_2'),
 (0.007831656763159741, 'PAR1EMPL_1'),
 (0.007782175246559954, 'FOMUSEUMX_2'),
 (0.00774113675204808, 'OWNRNTHB_1'),
 (0.007738780096832427, 'P1AGE_2'),
 (0.007735968000675989, 'P1AGE_3'),
 (0.00771952596692492, 'FOMUSEUMX_1'),
 (0.007717071667933685, 'NUMSIBSX_2'),
 (0.007614384126810291, 'FODINNERX_4'),
 (0.007547033877658494, 'P1SEX_2'),
 (0.0075220665947951446, 'P1SEX_1'),
 (0.007485902900980804, 'P2SEX_2'),
 (0.0072889784716724075, 'TTLHHINC_10'),
 (0.007286474982220974, 'P2SEX_1'),
 (0.0072538280784491165, 'HHTOTALXX_3'),
 (0.0072238838316628666, 'OWNRNTHB_2'),
 (0.007203401349121607, 'FODINNERX_3'),
 (0.007073895523618676, 'PAR1EMPL_4'),
 (0.006757952702827942, 'P2AGE_2'),
 (0.006673155595817891, 'TTLHHINC_12'),
 (0.0065705991777245286, 'P2MRSTA_1'),
 (0.006506591527337066, 'LRNCOMP_1'),
 (0.006416138103704371, 'LRNCOMP_2'),
 (0.006388704993834097, 'SEABSNT_2'),
 (0.00630614842925689, 'PAR1EMPL_2'),
 (0.00621219459357696, 'DISTASSI_2'),
 (0.006200762589693074, 'CSPEAKX_2'),
 (0.006168579879872212, 'TTLHHINC_7'),
 (0.006107130619440575, 'PAR2FTFY_3'),
 (0.006001724756749126, 'FOZOOX_2'),
 (0.005984978450585695, 'FOZOOX_1'),
 (0.005946235717186172, 'DISTASSI_1'),
 (0.0059177552609834365, 'CSPEAKX_4'),
 (0.005837861493402543, 'FODINNERX_6'),
 (0.005754021613391876, 'PAR1FTFY_3'),
 (0.005668455759751669, 'TTLHHINC_11'),
 (0.005539201987135694, 'TTLHHINC_4'),
 (0.005420947894227867, 'TTLHHINC_6'),
 (0.005372669738529408, 'TTLHHINC_5'),
 (0.0051647619963569496, 'FODINNERX_2'),
 (0.005107261761672094, 'P2REL_3'),
 (0.0049983154549963745, 'HHENGLISH_1'),
 (0.004830795302382317, 'SCHRTSCHL_2'),
 (0.004794519925787474, 'HHTOTALXX_6'),
 (0.004627951816060938, 'FHHOME_1'),
 (0.004625096270980819, 'P2AGE_4'),
 (0.0046238577093155615, 'HHENGLISH_2'),
 (0.004556330922636884, 'SCHRTSCHL_1'),
 (0.004493780603169843, 'TTLHHINC_3'),
 (0.004148403280718897, 'FCTEACHR_3'),
 (0.004106953010692235, 'CHLDNT_3'),
 (0.00398695233164749, 'TTLHHINC_2'),
 (0.0039060155052481225, 'FCSTDS_3'),
 (0.003704248257430901, 'SCHLMAGNET_2'),
 (0.0036692084516925915, 'FCSCHOOL_3'),
 (0.0036637009824128787, 'SCHLMAGNET_1'),
 (0.0035020785994039857, 'NUMSIBSX_3'),
 (0.0033679823135425117, 'P2MRSTA_5'),
 (0.0033382141316210183, 'P1REL_3'),
 (0.0033263619446225255, 'FODINNERX_1'),
 (0.003099354761825681, 'FODINNERX_0'),
 (0.00283626213856486, 'CSPEAKX_6'),
 (0.002760393677465409, 'P1AGE_4'),
 (0.0026363235251103214, 'SEENJOY_4'),
 (0.002518054020192269, 'P2REL_5'),
 (0.002513553158390816, 'CSPEAKX_3'),
 (0.002473694115962959, 'INTACC_1'),
 (0.0023295974576843666, 'SEABSNT_3'),
 (0.002266473165127194, 'HHTOTALXX_7'),
 (0.002067899707159307, 'HVINTCOM_2'),
 (0.0020617550570150517, 'INTACC_3'),
 (0.002019975386365694, 'P1REL_5'),
 (0.0019317045809281023, 'P2REL_2'),
 (0.0018591292808709469, 'P2MRSTA_3'),
 (0.0018235449181399023, 'P1REL_2'),
 (0.0018055044755550843, 'HVINTCOM_1'),
 (0.0014650932786708442, 'PAR1EMPL_3'),
 (0.001369334731637417, 'TTLHHINC_1'),
 (0.0013587546193480622, 'P2REL_6'),
 (0.0013486623140517144, 'FCTEACHR_4'),
 (0.0013468129689138963, 'NUMSIBSX_4'),
 (0.001296682489053422, 'CHLDNT_4'),
 (0.0011536382068356036, 'FCSTDS_4'),
 (0.0011094615179648574, 'FCSCHOOL_4'),
 (0.001049636902264199, 'HHPRTNRSX_0'),
 (0.00104037857625323, 'OWNRNTHB_3'),
 (0.001037695180186712, 'HHTOTALXX_8'),
 (0.0010297032416222737, 'SEABSNT_4'),
 (0.0010256558538541862, 'CSPEAKX_5'),
 (0.0009654807894200566, 'P1REL_6'),
 (0.0008863296931609978, 'HHPRTNRSX_1'),
 (0.0007326241658730636, 'HVINTSPHO_2'),
 (0.0007248138320870797, 'P2MRSTA_4'),
 (0.0007185488944406084, 'HVINTSPHO_1'),
 (0.0006560437142876551, 'EDCHSFL_1'),
 (0.0006142327430815384, 'NUMSIBSX_5'),
 (0.0005970522454264096, 'INTACC_2'),
 (0.0005840945768872725, 'EDCINTK12_2'),
 (0.0005532081979339827, 'EDCHSFL_2'),
 (0.0005525725782272264, 'HHTOTALXX_9'),
 (0.0004730895057706861, 'EDCINTK12_1'),
 (0.0004709752757932968, 'P2MRSTA_2'),
 (0.00045403745520591324, 'EDCPUB_2'),
 (0.0004352630288531562, 'EDCPUB_1'),
 (0.0003552494266033341, 'P2REL_4'),
 (0.00031037206528528586, 'P1REL_4'),
 (0.00021787787687781792, 'EDCPRI_2'),
 (0.00021042044603371694, 'EDCPRI_1'),
 (0.00015993815145419783, 'P1AGE_5'),
 (0.00015220220419012557, 'EDCCAT_2'),
 (0.00014186328117943536, 'HHTOTALXX_2'),
 (0.00012928445917806552, 'HHPRTNRSX_2'),
 (0.0001172177312091429, 'NUMSIBSX_6'),
 (0.0001106143778377704, 'INTACC_4'),
 (0.00010954564334711694, 'HHTOTALXX_10'),
 (8.08402810948483e-05, 'EDCCAT_1'),
 (7.924535272789929e-05, 'CSPEAKX_1'),
 (7.879499805458462e-05, 'P2AGE_5'),
 (4.760732412220451e-05, 'NUMSIBSX_7'),
 (2.6314326885575238e-05, 'P1AGE_1'),
 (2.446519270444295e-05, 'EDCREL_1'),
 (8.823368343398599e-06, 'EDCREL_2'),
 (5.376152547543842e-07, 'P2AGE_1'),
 (0.0, 'FHWKHRS_3')]

In [859]:
#print(importances)
Data= sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

#Creating a dataframe to filter by highest correlation and feature importance
feature_df=pd.DataFrame(Data,columns=["value","feature"])

#Trying to identify a number that will improve our outcome
feature_df=feature_df.loc[(feature_df["value"]>.0)]
feature_list= feature_df["feature"].tolist()


X = school_data_df[feature_list]
y = school_data_df['SEGRADES_1']

len(feature_list)

182

In [860]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [861]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
#X_scaler = scaler.fit(X_train)

# Scaling the data.
#X_train_scaled = X_scaler.transform(X_train)
#X_test_scaled = X_scaler.transform(X_test)

In [884]:
from sklearn.ensemble import GradientBoostingClassifier

learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]

for learning_rate in learning_rates:
    classifier = GradientBoostingClassifier(n_estimators=20,
    learning_rate=learning_rate,
    max_features=12,
    max_depth=3,
    random_state=0)
    classifier.fit(X_train, y_train)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(
           classifier.score(
               X_train,
               y_train)))
    print("Accuracy score (validation): {0:.3f}".format(
           classifier.score(
               X_test,
               y_test)))

Learning rate:  0.05
Accuracy score (training): 0.631
Accuracy score (validation): 0.615
Learning rate:  0.1
Accuracy score (training): 0.675
Accuracy score (validation): 0.662
Learning rate:  0.25
Accuracy score (training): 0.706
Accuracy score (validation): 0.686
Learning rate:  0.5
Accuracy score (training): 0.716
Accuracy score (validation): 0.679
Learning rate:  0.75
Accuracy score (training): 0.720
Accuracy score (validation): 0.683
Learning rate:  1
Accuracy score (training): 0.718
Accuracy score (validation): 0.674

In [881]:
# Choose a learning rate and create classifier
classifier = GradientBoostingClassifier(n_estimators=20,
                                        learning_rate=1,
                                        max_features=12,
                                        max_depth=3,
                                        random_state=0)

# Fit the model
classifier.fit(X_train, y_train)

# Make Prediction
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).head(20)

      Prediction  Actual
4916           1       1
2844           1       1
7984           1       1
6356           0       0
1228           0       1
7770           1       1
6744           1       1
287            0       1
3691           0       0
3952           1       1
6481           0       0
5389           0       0
2582           1       1
5418           0       1
4457           1       0
4811           0       0
4236           1       0
7168           1       0
1168           1       1
2990           1       1

In [882]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.6740067017711824

In [883]:
# Generate the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"],
    columns=["Predicted 0", "Predicted 1"]
)

# Displaying results
display(cm_df)

          Predicted 0  Predicted 1
Actual 0          414          434
Actual 1          247          994

In [870]:
# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

In [871]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)

In [872]:
# Calculating the confusion matrix.
#we analyze how well our random forest model classifies loan applications
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0          394          454
Actual 1          206         1035

In [873]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [874]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0          394          454
Actual 1          206         1035

Accuracy Score : 0.6840593585447583
Classification Report
              precision    recall  f1-score   support

           0       0.66      0.46      0.54       848
           1       0.70      0.83      0.76      1241

    accuracy                           0.68      2089
   macro avg       0.68      0.65      0.65      2089
weighted avg       0.68      0.68      0.67      2089

In [739]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.06335113528677254, 'SEENJOY_1'),
 (0.02803879393750853, 'SEENJOY_3'),
 (0.02523669256303347, 'FCTEACHR_1'),
 (0.023782630006850516, 'FCSCHOOL_1'),
 (0.02190760117506135, 'FHHOME_4'),
 (0.02128150501098831, 'SEENJOY_2'),
 (0.020735650548094817, 'P2REL_1'),
 (0.016897957295406277, 'P1REL_1'),
 (0.016744442075781782, 'SEABSNT_1'),
 (0.014835337356093343, 'FCSTDS_1'),
 (0.011844882254962302, 'P2MRSTA_1'),
 (0.011753085526724478, 'FCSCHOOL_2'),
 (0.011412307758055767, 'FCTEACHR_2'),
 (0.011192040219047171, 'FOBOOKSTX_2'),
 (0.011111793013626943, 'FOBOOKSTX_1'),
 (0.011092403668356565, 'OWNRNTHB_1'),
 (0.010402659966652267, 'OWNRNTHB_2'),
 (0.009625846181764866, 'FOGROUPX_1'),
 (0.009515896978251528, 'FOCONCRTX_2'),
 (0.009481219082065678, 'P2AGE_3'),
 (0.009364244199534761, 'SEABSNT_2'),
 (0.009328651925312164, 'FHHOME_3'),
 (0.00926634128002574, 'CENREG_4'),
 (0.009164773457766177, 'FOCONCRTX_1'),
 (0.009162980757270598, 'FHHOME_2'),
 (0.00915748275874418, 'FOGROUPX_2'),
 (0.009037651569931988, 'CSPEAKX_4'),
 (0.009006539156030951, 'FODINNERX_7'),
 (0.008612037581015954, 'FOLIBRAYX_2'),
 (0.008428123367868277, 'CENREG_2'),
 (0.008420545114264948, 'PAR2FTFY_1'),
 (0.008352111844842735, 'FOLIBRAYX_1'),
 (0.008345108757048575, 'FOGAMES_1'),
 (0.008337791687102865, 'HHTOTALXX_4'),
 (0.008332544641405103, 'TTLHHINC_12'),
 (0.008276229535837488, 'LRNTAB_1'),
 (0.008259677405321603, 'LRNTAB_2'),
 (0.008254073849349347, 'CHLDNT_1'),
 (0.008177910857946722, 'FORESPON_1'),
 (0.008161208180573688, 'FOSTORY2X_1'),
 (0.008126705865150054, 'FOSTORY2X_2'),
 (0.008043196347273653, 'FOBUILDX_1'),
 (0.007994710536912494, 'CHLDNT_2'),
 (0.007989602232762056, 'FOBUILDX_2'),
 (0.007974024530502315, 'NUMSIBSX_1'),
 (0.00791075170927751, 'CSPEAKX_2'),
 (0.007895544674345627, 'FOHISTX_2'),
 (0.00784425419274947, 'FOMUSEUMX_2'),
 (0.007798913988871294, 'FOSPORT_1'),
 (0.007797416343474502, 'NUMSIBSX_0'),
 (0.007770090092963526, 'FCSTDS_2'),
 (0.007681197419884512, 'FOGAMES_2'),
 (0.007650968167881811, 'FORESPON_2'),
 (0.0076108606868479905, 'FOMUSEUMX_1'),
 (0.007536471279388316, 'FOSPORT_2'),
 (0.007519476341846143, 'FOHISTX_1'),
 (0.007428671700640398, 'P1AGE_3'),
 (0.007422287226274759, 'FOCRAFTS_1'),
 (0.007330316415905497, 'FOCRAFTS_2'),
 (0.007129679006456556, 'TTLHHINC_4'),
 (0.00712152314123645, 'LRNCELL_1'),
 (0.007114327189116401, 'FODINNERX_5'),
 (0.007082440022555151, 'PAR1EMPL_4'),
 (0.00707461040515253, 'PAR2FTFY_3'),
 (0.007020500008241432, 'TTLHHINC_11'),
 (0.007011597350923206, 'LRNCELL_2'),
 (0.006999153494683111, 'PAR1FTFY_1'),
 (0.006918079874493631, 'P2SEX_2'),
 (0.006886323118969721, 'CENREG_3'),
 (0.006854254189612555, 'HHTOTALXX_3'),
 (0.006796892447315202, 'P1AGE_2'),
 (0.006754187361219799, 'LRNCOMP_2'),
 (0.006737884471272394, 'TTLHHINC_9'),
 (0.006706591577449831, 'PAR1FTFY_2'),
 (0.006690289549036311, 'P2AGE_4'),
 (0.006687553577685851, 'PAR2FTFY_2'),
 (0.006676619382692946, 'P1SEX_1'),
 (0.0066494382025804755, 'PAR1EMPL_1'),
 (0.006622138593646218, 'P2AGE_2'),
 (0.006612780045340767, 'HHTOTALXX_5'),
 (0.006526553577337772, 'TTLHHINC_5'),
 (0.006526509045718446, 'NUMSIBSX_2'),
 (0.006524941750476491, 'PAR1FTFY_3'),
 (0.006507428714485611, 'P2REL_3'),
 (0.006496828758663078, 'P2SEX_1'),
 (0.0064581454368157825, 'LRNCOMP_1'),
 (0.006385926421267082, 'CENREG_1'),
 (0.0063404771375307, 'P1SEX_2'),
 (0.006330831325848285, 'HHENGLISH_1'),
 (0.006329664254143567, 'TTLHHINC_8'),
 (0.00632690926826435, 'FODINNERX_4'),
 (0.006276401885027806, 'TTLHHINC_3'),
 (0.006242871904219965, 'FCTEACHR_3'),
 (0.006219776621602399, 'FODINNERX_3'),
 (0.006218467318901719, 'HHENGLISH_2'),
 (0.006018968752941533, 'TTLHHINC_10'),
 (0.00576499479914117, 'TTLHHINC_7'),
 (0.005737171278634685, 'FOZOOX_2'),
 (0.005714834190085621, 'DISTASSI_1'),
 (0.005575134313610095, 'FOZOOX_1'),
 (0.00556611319515728, 'FHHOME_1'),
 (0.005560376951053538, 'PAR1EMPL_2'),
 (0.005530730466436801, 'HHTOTALXX_6'),
 (0.005327541356347793, 'SCHRTSCHL_1'),
 (0.005322933034511825, 'DISTASSI_2'),
 (0.005186026826836352, 'TTLHHINC_6'),
 (0.0048327221044695105, 'SCHRTSCHL_2'),
 (0.004549963720646828, 'FODINNERX_2'),
 (0.004237715836631768, 'FODINNERX_6'),
 (0.00420080915826735, 'CHLDNT_3')]