In [1]:
# import dependencies
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
# load csv
mydata_load = "../Resources/nhes_19_pfi_cleaned.csv"
school_data_df = pd.read_csv(mydata_load)
school_data_df = pd.DataFrame(school_data_df)

In [3]:
list(school_data_df.columns)

['Unnamed: 0',
 'ALLGRADEX_2',
 'ALLGRADEX_3',
 'ALLGRADEX_4',
 'ALLGRADEX_5',
 'ALLGRADEX_6',
 'ALLGRADEX_7',
 'ALLGRADEX_8',
 'ALLGRADEX_9',
 'ALLGRADEX_10',
 'ALLGRADEX_11',
 'ALLGRADEX_12',
 'ALLGRADEX_13',
 'ALLGRADEX_14',
 'ALLGRADEX_15',
 'SEGRADES_0',
 'SEGRADES_1',
 'CENREG_1',
 'CENREG_2',
 'CENREG_3',
 'CENREG_4',
 'EDCPUB_1',
 'EDCPUB_2',
 'EDCCAT_1',
 'EDCCAT_2',
 'EDCREL_1',
 'EDCREL_2',
 'EDCPRI_1',
 'EDCPRI_2',
 'EDCINTK12_1',
 'EDCINTK12_2',
 'EDCHSFL_1',
 'EDCHSFL_2',
 'DISTASSI_1',
 'DISTASSI_2',
 'SCHRTSCHL_1',
 'SCHRTSCHL_2',
 'SCHLMAGNET_1',
 'SCHLMAGNET_2',
 'SEENJOY_1',
 'SEENJOY_2',
 'SEENJOY_3',
 'SEENJOY_4',
 'SEABSNT_1',
 'SEABSNT_2',
 'SEABSNT_3',
 'SEABSNT_4',
 'FCSCHOOL_1',
 'FCSCHOOL_2',
 'FCSCHOOL_3',
 'FCSCHOOL_4',
 'FCTEACHR_1',
 'FCTEACHR_2',
 'FCTEACHR_3',
 'FCTEACHR_4',
 'FCSTDS_1',
 'FCSTDS_2',
 'FCSTDS_3',
 'FCSTDS_4',
 'FHHOME_1',
 'FHHOME_2',
 'FHHOME_3',
 'FHHOME_4',
 'FHWKHRS_1',
 'FHWKHRS_2',
 'FHWKHRS_3',
 'FHWKHRS_4',
 'FOSTORY2X_1',
 'FOSTORY2X_2',
 'FOCRAFTS_1',
 'FOCRAFTS_2',
 'FOGAMES_1',
 'FOGAMES_2',
 'FOBUILDX_1',
 'FOBUILDX_2',
 'FOSPORT_1',
 'FOSPORT_2',
 'FORESPON_1',
 'FORESPON_2',
 'FOHISTX_1',
 'FOHISTX_2',
 'FODINNERX_0',
 'FODINNERX_1',
 'FODINNERX_2',
 'FODINNERX_3',
 'FODINNERX_4',
 'FODINNERX_5',
 'FODINNERX_6',
 'FODINNERX_7',
 'FOLIBRAYX_1',
 'FOLIBRAYX_2',
 'FOBOOKSTX_1',
 'FOBOOKSTX_2',
 'FOCONCRTX_1',
 'FOCONCRTX_2',
 'FOMUSEUMX_1',
 'FOMUSEUMX_2',
 'FOZOOX_1',
 'FOZOOX_2',
 'FOGROUPX_1',
 'FOGROUPX_2',
 'HHENGLISH_1',
 'HHENGLISH_2',
 'CSPEAKX_1',
 'CSPEAKX_2',
 'CSPEAKX_3',
 'CSPEAKX_4',
 'CSPEAKX_5',
 'CSPEAKX_6',
 'HHTOTALXX_2',
 'HHTOTALXX_3',
 'HHTOTALXX_4',
 'HHTOTALXX_5',
 'HHTOTALXX_6',
 'HHTOTALXX_7',
 'HHTOTALXX_8',
 'HHTOTALXX_9',
 'HHTOTALXX_10',
 'HHPRTNRSX_0',
 'HHPRTNRSX_1',
 'HHPRTNRSX_2',
 'P1REL_1',
 'P1REL_2',
 'P1REL_3',
 'P1REL_4',
 'P1REL_5',
 'P1REL_6',
 'P1SEX_1',
 'P1SEX_2',
 'P1AGE_1',
 'P1AGE_2',
 'P1AGE_3',
 'P1AGE_4',
 'P1AGE_5',
 'P2AGE_1',
 'P2AGE_2',
 'P2AGE_3',
 'P2AGE_4',
 'P2AGE_5',
 'P2REL_1',
 'P2REL_2',
 'P2REL_3',
 'P2REL_4',
 'P2REL_5',
 'P2REL_6',
 'P2SEX_1',
 'P2SEX_2',
 'P2MRSTA_1',
 'P2MRSTA_2',
 'P2MRSTA_3',
 'P2MRSTA_4',
 'P2MRSTA_5',
 'PAR1EMPL_1',
 'PAR1EMPL_2',
 'PAR1EMPL_3',
 'PAR1EMPL_4',
 'PAR1FTFY_1',
 'PAR1FTFY_2',
 'PAR1FTFY_3',
 'PAR2FTFY_1',
 'PAR2FTFY_2',
 'PAR2FTFY_3',
 'NUMSIBSX_0',
 'NUMSIBSX_1',
 'NUMSIBSX_2',
 'NUMSIBSX_3',
 'NUMSIBSX_4',
 'NUMSIBSX_5',
 'NUMSIBSX_6',
 'NUMSIBSX_7',
 'TTLHHINC_1',
 'TTLHHINC_2',
 'TTLHHINC_3',
 'TTLHHINC_4',
 'TTLHHINC_5',
 'TTLHHINC_6',
 'TTLHHINC_7',
 'TTLHHINC_8',
 'TTLHHINC_9',
 'TTLHHINC_10',
 'TTLHHINC_11',
 'TTLHHINC_12',
 'OWNRNTHB_1',
 'OWNRNTHB_2',
 'OWNRNTHB_3',
 'HVINTSPHO_1',
 'HVINTSPHO_2',
 'HVINTCOM_1',
 'HVINTCOM_2',
 'INTACC_1',
 'INTACC_2',
 'INTACC_3',
 'INTACC_4',
 'CHLDNT_1',
 'CHLDNT_2',
 'CHLDNT_3',
 'CHLDNT_4',
 'LRNCOMP_1',
 'LRNCOMP_2',
 'LRNTAB_1',
 'LRNTAB_2',
 'LRNCELL_1',
 'LRNCELL_2']

In [4]:
#Creating a correlation matrix
school_data_df.corr()

,Unnamed: 0,ALLGRADEX_2,ALLGRADEX_3,ALLGRADEX_4,ALLGRADEX_5,ALLGRADEX_6,ALLGRADEX_7,ALLGRADEX_8,ALLGRADEX_9,ALLGRADEX_10,...,CHLDNT_1,CHLDNT_2,CHLDNT_3,CHLDNT_4,LRNCOMP_1,LRNCOMP_2,LRNTAB_1,LRNTAB_2,LRNCELL_1,LRNCELL_2
Unnamed: 0,1.000000,-0.004912,0.014405,0.002421,-0.004935,0.016563,-0.008261,0.022519,-0.017663,-0.007524,...,-0.013632,0.026594,-0.026862,0.008036,-0.000466,0.000466,0.000165,-0.000165,-0.008124,0.008124
ALLGRADEX_2,-0.004912,1.000000,-0.006402,-0.032678,-0.034512,-0.038738,-0.041822,-0.043716,-0.048887,-0.050667,...,-0.068595,0.042823,0.060310,-0.012201,-0.126457,0.126457,0.076277,-0.076277,-0.078834,0.078834
ALLGRADEX_3,0.014405,-0.006402,1.000000,-0.007956,-0.008403,-0.009432,-0.010183,-0.010644,-0.011903,-0.012336,...,-0.029338,0.011517,0.038295,-0.004582,-0.033743,0.033743,0.015063,-0.015063,-0.015423,0.015423
ALLGRADEX_4,0.002421,-0.032678,-0.007956,1.000000,-0.042893,-0.048145,-0.051977,-0.054332,-0.060759,-0.062970,...,-0.108477,0.071380,0.068013,0.025200,-0.152580,0.152580,0.092211,-0.092211,-0.098630,0.098630
ALLGRADEX_5,-0.004935,-0.034512,-0.008403,-0.042893,1.000000,-0.050848,-0.054895,-0.057382,-0.064170,-0.066505,...,-0.084530,0.054461,0.051958,0.026646,-0.095328,0.095328,0.103295,-0.103295,-0.119507,0.119507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
LRNCOMP_2,0.000466,0.126457,0.033743,0.152580,0.095328,0.051115,0.050869,0.013389,0.001417,-0.029208,...,-0.118696,0.082591,0.057356,0.046304,-1.000000,1.000000,0.122631,-0.122631,-0.111387,0.111387
LRNTAB_1,0.000165,0.076277,0.015063,0.092211,0.103295,0.095523,0.089603,0.080283,0.018992,-0.020179,...,0.019360,-0.011814,-0.004746,-0.024347,-0.122631,0.122631,1.000000,-1.000000,-0.022079,0.022079
LRNTAB_2,-0.000165,-0.076277,-0.015063,-0.092211,-0.103295,-0.095523,-0.089603,-0.080283,-0.018992,0.020179,...,-0.019360,0.011814,0.004746,0.024347,0.122631,-0.122631,-1.000000,1.000000,0.022079,-0.022079
LRNCELL_1,-0.008124,-0.078834,-0.015423,-0.098630,-0.119507,-0.147114,-0.152877,-0.098744,-0.042718,0.009202,...,0.210928,-0.166484,-0.093787,-0.019327,0.111387,-0.111387,-0.022079,0.022079,1.000000,-1.000000
LRNCELL_2,0.008124,0.078834,0.015423,0.098630,0.119507,0.147114,0.152877,0.098744,0.042718,-0.009202,...,-0.210928,0.166484,0.093787,0.019327,-0.111387,0.111387,0.022079,-0.022079,-1.000000,1.000000

In [5]:
# remove allgrade columns and preserve in a separate df
allgrade_df = school_data_df.filter(['ALLGRADEX_2',
 'ALLGRADEX_3',
 'ALLGRADEX_4',
 'ALLGRADEX_5',
 'ALLGRADEX_6',
 'ALLGRADEX_7',
 'ALLGRADEX_8',
 'ALLGRADEX_9',
 'ALLGRADEX_10',
 'ALLGRADEX_11',
 'ALLGRADEX_12',
 'ALLGRADEX_13',
 'ALLGRADEX_14',
 'ALLGRADEX_15'], axis=1)
allgrade_df.head()

,ALLGRADEX_2,ALLGRADEX_3,ALLGRADEX_4,ALLGRADEX_5,ALLGRADEX_6,ALLGRADEX_7,ALLGRADEX_8,ALLGRADEX_9,ALLGRADEX_10,ALLGRADEX_11,ALLGRADEX_12,ALLGRADEX_13,ALLGRADEX_14,ALLGRADEX_15
0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [6]:
# remove allgrade columns from school_data_df
school_data_df = school_data_df.drop([ 'ALLGRADEX_2',
 'ALLGRADEX_3',
 'ALLGRADEX_4',
 'ALLGRADEX_5',
 'ALLGRADEX_6',
 'ALLGRADEX_7',
 'ALLGRADEX_8',
 'ALLGRADEX_9',
 'ALLGRADEX_10',
 'ALLGRADEX_11',
 'ALLGRADEX_12',
 'ALLGRADEX_13',
 'ALLGRADEX_14',
 'ALLGRADEX_15'], axis=1)

In [7]:
# create features
X = school_data_df.drop(columns = {'SEGRADES_0', 'Unnamed: 0','SEGRADES_1'}, axis=1)

# create target
y = school_data_df['SEGRADES_1']

In [8]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [9]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [11]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [12]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [13]:
# Calculating the confusion matrix.
#we analyze how well our random forest model classifies
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0          390          458
Actual 1          211         1030

In [14]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
print(f'Accuracy: {acc_score: .2f}')

Accuracy:  0.68

In [15]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0          390          458
Actual 1          211         1030

Accuracy Score : 0.6797510770703686
Classification Report
              precision    recall  f1-score   support

           0       0.65      0.46      0.54       848
           1       0.69      0.83      0.75      1241

    accuracy                           0.68      2089
   macro avg       0.67      0.64      0.65      2089
weighted avg       0.67      0.68      0.67      2089

In [16]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_

# We can sort the features by their importance.
sorted(zip(importances, X.columns), reverse=True)

[(0.028499974934804485, 'SEENJOY_1'),
 (0.014829507131542482, 'SEENJOY_3'),
 (0.013756947688883036, 'FHHOME_4'),
 (0.013284346738801783, 'FCTEACHR_1'),
 (0.013180244114844643, 'SEENJOY_2'),
 (0.012730782982643489, 'FCSCHOOL_1'),
 (0.011915634325641534, 'P2REL_1'),
 (0.011099895479714943, 'SEABSNT_1'),
 (0.010314973747041916, 'CHLDNT_2'),
 (0.010300531860800124, 'CENREG_2'),
 (0.010290256851613935, 'FHHOME_3'),
 (0.009958729217046972, 'LRNTAB_1'),
 (0.009909056489200088, 'LRNTAB_2'),
 (0.009884266350575857, 'FOGROUPX_1'),
 (0.009876263633943224, 'FODINNERX_7'),
 (0.00987495296615884, 'FOBUILDX_1'),
 (0.00984581251574532, 'CHLDNT_1'),
 (0.009784960158704331, 'FOBUILDX_2'),
 (0.009738276334816883, 'FOSTORY2X_2'),
 (0.009615731934165251, 'FOSTORY2X_1'),
 (0.009596649861286746, 'FCSTDS_1'),
 (0.009572542114271684, 'FOGROUPX_2'),
 (0.00952941073065696, 'CENREG_4'),
 (0.009511821057412932, 'FOHISTX_1'),
 (0.009503892982455195, 'FOCONCRTX_2'),
 (0.00946677129158655, 'FOHISTX_2'),
 (0.009322106291079258, 'FOSPORT_2'),
 (0.00925345203280464, 'PAR2FTFY_1'),
 (0.009200847700557228, 'TTLHHINC_9'),
 (0.009200782850771345, 'FOSPORT_1'),
 (0.009193174968883713, 'NUMSIBSX_1'),
 (0.009189417417009686, 'HHTOTALXX_4'),
 (0.009154279476786034, 'FODINNERX_5'),
 (0.009082893126435775, 'FOGAMES_2'),
 (0.008950247489471045, 'FOGAMES_1'),
 (0.008942551309094287, 'FOCONCRTX_1'),
 (0.008883809719834547, 'FOBOOKSTX_2'),
 (0.008870577417380487, 'LRNCELL_2'),
 (0.008858730903806076, 'FORESPON_2'),
 (0.008803669284839695, 'FORESPON_1'),
 (0.008787868310578189, 'LRNCELL_1'),
 (0.008756169238688955, 'CENREG_3'),
 (0.008740491956866464, 'FOLIBRAYX_1'),
 (0.008665157467861256, 'FHHOME_2'),
 (0.008604378519210691, 'FOCRAFTS_1'),
 (0.00859413085437832, 'FOCRAFTS_2'),
 (0.008443979582563514, 'TTLHHINC_8'),
 (0.00842655519911583, 'FOBOOKSTX_1'),
 (0.008398817520754028, 'PAR1FTFY_1'),
 (0.008394088946334049, 'FOLIBRAYX_2'),
 (0.008371728138855809, 'P1AGE_3'),
 (0.008204052116050664, 'FCTEACHR_2'),
 (0.00817081753793649, 'P2AGE_3'),
 (0.00814099118889231, 'NUMSIBSX_0'),
 (0.008083657058209204, 'CENREG_1'),
 (0.008064084510104864, 'FODINNERX_4'),
 (0.007926358339354019, 'HHTOTALXX_5'),
 (0.007837020496607006, 'PAR1EMPL_1'),
 (0.007802752788411478, 'P2SEX_2'),
 (0.007793946574991307, 'FCSCHOOL_2'),
 (0.00774525163506405, 'P1REL_1'),
 (0.0077338718001271674, 'PAR2FTFY_2'),
 (0.0076643388415376665, 'P1AGE_2'),
 (0.007589189008678375, 'OWNRNTHB_1'),
 (0.007500466734692492, 'FOMUSEUMX_1'),
 (0.007488615182505508, 'HHTOTALXX_3'),
 (0.007457105110529402, 'OWNRNTHB_2'),
 (0.0074388229823593105, 'SEABSNT_2'),
 (0.00742976430619446, 'PAR1FTFY_2'),
 (0.007413094846206716, 'FOMUSEUMX_2'),
 (0.007337082865828158, 'FODINNERX_3'),
 (0.0073019266712145885, 'P2SEX_1'),
 (0.007126079808007886, 'P1SEX_1'),
 (0.007058804274222844, 'P1SEX_2'),
 (0.0070478155171806445, 'TTLHHINC_10'),
 (0.00704768717067935, 'NUMSIBSX_2'),
 (0.0069476365958670286, 'FCSTDS_2'),
 (0.006845231698336963, 'P2AGE_2'),
 (0.006741598379441409, 'LRNCOMP_1'),
 (0.00655001106628438, 'CSPEAKX_2'),
 (0.006493971250135181, 'PAR2FTFY_3'),
 (0.006452587066003734, 'DISTASSI_2'),
 (0.006414975052092564, 'TTLHHINC_7'),
 (0.006349576824014428, 'FOZOOX_2'),
 (0.006335829109310313, 'PAR1EMPL_4'),
 (0.006279324030403134, 'DISTASSI_1'),
 (0.0062380316182834095, 'TTLHHINC_12'),
 (0.006195019595954113, 'LRNCOMP_2'),
 (0.005987132537268814, 'PAR1EMPL_2'),
 (0.005877229547260366, 'FOZOOX_1'),
 (0.0058283871056605645, 'P2MRSTA_1'),
 (0.0056971724579001105, 'CSPEAKX_4'),
 (0.00553018239921139, 'PAR1FTFY_3'),
 (0.005481625821597963, 'TTLHHINC_11'),
 (0.005173698738576271, 'TTLHHINC_6'),
 (0.005038280193020308, 'FODINNERX_6'),
 (0.005038197474943913, 'SCHRTSCHL_1'),
 (0.005009192806510581, 'TTLHHINC_4'),
 (0.0049975524985882485, 'FHHOME_1'),
 (0.004994362907056844, 'TTLHHINC_5'),
 (0.004887136032034047, 'P2REL_3'),
 (0.004847509027376947, 'FODINNERX_2'),
 (0.004838302564110219, 'HHENGLISH_1'),
 (0.0048013613902098615, 'SCHRTSCHL_2'),
 (0.004701749355572263, 'HHTOTALXX_6'),
 (0.004417917489900473, 'CHLDNT_3'),
 (0.004259736213754625, 'HHENGLISH_2'),
 (0.0042063273703187715, 'P2AGE_4'),
 (0.004112374332901766, 'TTLHHINC_3'),
 (0.003966050003747576, 'TTLHHINC_2'),
 (0.0037610561195722497, 'SCHLMAGNET_2'),
 (0.0037196769205252015, 'SCHLMAGNET_1'),
 (0.00368403116706414, 'FCTEACHR_3'),
 (0.0036255096998331505, 'FCSTDS_3'),
 (0.003453319045123885, 'FODINNERX_0'),
 (0.003372416479704596, 'P2MRSTA_5'),
 (0.003346475600113766, 'NUMSIBSX_3'),
 (0.003345029844727236, 'FODINNERX_1'),
 (0.0032862116116734257, 'FHWKHRS_1'),
 (0.0032199137586427424, 'FHWKHRS_2'),
 (0.0032013927146801848, 'P1REL_3'),
 (0.0028058995010575697, 'CSPEAKX_6'),
 (0.002797059117843423, 'FCSCHOOL_3'),
 (0.002793119237151656, 'P2REL_5'),
 (0.0027236332684655914, 'P1AGE_4'),
 (0.0027197486234262404, 'SEABSNT_3'),
 (0.0026916069200538005, 'SEENJOY_4'),
 (0.002686543337181646, 'CSPEAKX_3'),
 (0.00257653788579153, 'INTACC_1'),
 (0.0025018170292985227, 'HHTOTALXX_7'),
 (0.002372259893837952, 'P1REL_5'),
 (0.0018921578922557502, 'INTACC_3'),
 (0.0018711611131553947, 'P2MRSTA_3'),
 (0.0018447600235101179, 'HVINTCOM_1'),
 (0.001841113985861892, 'P2REL_2'),
 (0.0018189512372798753, 'P1REL_2'),
 (0.0017809686651524827, 'HVINTCOM_2'),
 (0.0015648910379911039, 'PAR1EMPL_3'),
 (0.0014464049871798935, 'FCSCHOOL_4'),
 (0.0014151317316117703, 'TTLHHINC_1'),
 (0.0014068193799487748, 'FCSTDS_4'),
 (0.0013627505782223964, 'SEABSNT_4'),
 (0.0012612658269739738, 'NUMSIBSX_4'),
 (0.0012500132288876145, 'CHLDNT_4'),
 (0.0011860807204841697, 'P2REL_6'),
 (0.0010541803784988478, 'HHPRTNRSX_0'),
 (0.001052753953083562, 'CSPEAKX_5'),
 (0.0010373218766417031, 'FCTEACHR_4'),
 (0.0010181258246207932, 'HVINTSPHO_1'),
 (0.001005724934306089, 'HVINTSPHO_2'),
 (0.0009866746377077415, 'INTACC_2'),
 (0.0009336715992575566, 'HHPRTNRSX_1'),
 (0.0009270451862767704, 'P1REL_6'),
 (0.0008828810954863121, 'HHTOTALXX_8'),
 (0.0007811208622368378, 'OWNRNTHB_3'),
 (0.0006613215652873003, 'P2MRSTA_2'),
 (0.0006281974328787506, 'EDCINTK12_2'),
 (0.0005998654130796413, 'P2MRSTA_4'),
 (0.0005824326561940694, 'HHTOTALXX_9'),
 (0.0005763723063026149, 'EDCINTK12_1'),
 (0.0005332845487283682, 'EDCHSFL_2'),
 (0.0005113473416845449, 'NUMSIBSX_5'),
 (0.00043937689924598573, 'EDCHSFL_1'),
 (0.00043553732800715795, 'EDCPUB_1'),
 (0.00036256684922618534, 'EDCPUB_2'),
 (0.00034559838426363455, 'P1AGE_5'),
 (0.0003160352791864759, 'P1REL_4'),
 (0.0002931405830401094, 'P2REL_4'),
 (0.0002561281358552886, 'EDCPRI_1'),
 (0.00023092439052906734, 'EDCPRI_2'),
 (0.00021097142097681947, 'HHTOTALXX_2'),
 (0.00021034550798453526, 'HHTOTALXX_10'),
 (0.00020768901327667378, 'FHWKHRS_4'),
 (0.00017271410275784528, 'EDCCAT_2'),
 (0.00016839600289281914, 'HHPRTNRSX_2'),
 (0.00015452788206702959, 'P2AGE_5'),
 (0.00013514350222567107, 'EDCCAT_1'),
 (0.00013466260330161748, 'FHWKHRS_3'),
 (0.00012944049534312004, 'CSPEAKX_1'),
 (0.00012187552625794662, 'NUMSIBSX_6'),
 (0.00010463207149019337, 'EDCREL_1'),
 (9.964188570540017e-05, 'EDCREL_2'),
 (7.950488387421079e-05, 'INTACC_4'),
 (5.371885366199439e-05, 'NUMSIBSX_7'),
 (3.0353906889601734e-05, 'P1AGE_1'),
 (8.017557830705867e-06, 'P2AGE_1')]

In [17]:
# assign importances to variable
Data= sorted(zip(importances, X.columns), reverse=True)

#Creating a dataframe to hold feature importances
feature_df=pd.DataFrame(Data,columns=["value","feature"])

#Trying to identify a number that will improve our outcome
feature_df=feature_df.loc[(feature_df["value"]>.0015)]
feature_list= feature_df["feature"].tolist()

len(feature_list)

138

In [18]:
# create features from higher feature importances
X = school_data_df[feature_list]

# create target
y = school_data_df['SEGRADES_1']

In [19]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [20]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [22]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [23]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [24]:
# Generate the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"],
    columns=["Predicted 0", "Predicted 1"]
)

In [25]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {accuracy_score(y_test, predictions)}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0          411          437
Actual 1          214         1027

Accuracy Score : 0.688367640019148
Classification Report
              precision    recall  f1-score   support

           0       0.66      0.48      0.56       848
           1       0.70      0.83      0.76      1241

    accuracy                           0.69      2089
   macro avg       0.68      0.66      0.66      2089
weighted avg       0.68      0.69      0.68      2089