In [233]:
# PyCitySchools_Challenge.ipynb
# See README for background, objectives & instructions!!

# Add the Pandas dependency.
import pandas as pd

# Add the numpy dependency.
import numpy as np

In [234]:
mydata_load = "../Resources/nhes_merged_pfi_cleaned.csv"
school_data_df = pd.read_csv(mydata_load)
len(school_data_df)

25178

In [235]:
#school_data_df.head(5)
list(school_data_df.columns)
#school_data_df.head(5)

['Unnamed: 0',
 'SEGRADES_0',
 'SEGRADES_1',
 'CENREG_1',
 'CENREG_2',
 'CENREG_3',
 'CENREG_4',
 'SCHRTSCHL_1',
 'SCHRTSCHL_2',
 'SEENJOY_1',
 'SEENJOY_2',
 'SEENJOY_3',
 'SEENJOY_4',
 'SEABSNT_0',
 'SEABSNT_1',
 'SEABSNT_2',
 'SEABSNT_3',
 'SEABSNT_4',
 'SEABSNT_5',
 'SEABSNT_6',
 'SEABSNT_7',
 'SEABSNT_8',
 'SEABSNT_9',
 'SEABSNT_10',
 'SEABSNT_11',
 'SEABSNT_12',
 'SEABSNT_13',
 'SEABSNT_14',
 'SEABSNT_15',
 'SEABSNT_16',
 'SEABSNT_17',
 'SEABSNT_18',
 'SEABSNT_19',
 'SEABSNT_20',
 'SEABSNT_21',
 'SEABSNT_22',
 'SEABSNT_23',
 'SEABSNT_24',
 'SEABSNT_25',
 'SEABSNT_26',
 'SEABSNT_27',
 'SEABSNT_28',
 'SEABSNT_29',
 'SEABSNT_30',
 'SEABSNT_33',
 'SEABSNT_34',
 'SEABSNT_35',
 'SEABSNT_37',
 'SEABSNT_39',
 'SEABSNT_40',
 'SEABSNT_42',
 'SEABSNT_43',
 'SEABSNT_44',
 'SEABSNT_45',
 'SEABSNT_48',
 'SEABSNT_50',
 'SEABSNT_52',
 'SEABSNT_60',
 'SEABSNT_63',
 'SEABSNT_65',
 'SEABSNT_72',
 'SEABSNT_75',
 'SEABSNT_76',
 'SEABSNT_80',
 'SEABSNT_90',
 'SEABSNT_92',
 'SEABSNT_100',
 'SEABSNT_130',
 'SEABSNT_167',
 'FCSCHOOL_1',
 'FCSCHOOL_2',
 'FCSCHOOL_3',
 'FCSCHOOL_4',
 'FCTEACHR_1',
 'FCTEACHR_2',
 'FCTEACHR_3',
 'FCTEACHR_4',
 'FCSTDS_1',
 'FCSTDS_2',
 'FCSTDS_3',
 'FCSTDS_4',
 'FHHOME_1',
 'FHHOME_2',
 'FHHOME_3',
 'FHHOME_4',
 'FHWKHRS_1',
 'FHWKHRS_2',
 'FHWKHRS_3',
 'FHWKHRS_4',
 'FOSTORY2X_1',
 'FOSTORY2X_2',
 'FOCRAFTS_1',
 'FOCRAFTS_2',
 'FOGAMES_1',
 'FOGAMES_2',
 'FOBUILDX_1',
 'FOBUILDX_2',
 'FOSPORT_1',
 'FOSPORT_2',
 'FORESPON_1',
 'FORESPON_2',
 'FOHISTX_1',
 'FOHISTX_2',
 'FODINNERX_1',
 'FODINNERX_2',
 'FODINNERX_3',
 'FODINNERX_4',
 'FOLIBRAYX_1',
 'FOLIBRAYX_2',
 'FOBOOKSTX_1',
 'FOBOOKSTX_2',
 'FOCONCRTX_1',
 'FOCONCRTX_2',
 'FOMUSEUMX_1',
 'FOMUSEUMX_2',
 'FOZOOX_1',
 'FOZOOX_2',
 'FOGROUPX_1',
 'FOGROUPX_2',
 'HHENGLISH_1',
 'HHENGLISH_2',
 'CSPEAKX_1',
 'CSPEAKX_2',
 'CSPEAKX_3',
 'CSPEAKX_4',
 'CSPEAKX_5',
 'CSPEAKX_6',
 'P1REL_1',
 'P1REL_2',
 'P1REL_3',
 'P1REL_4',
 'P1REL_5',
 'P1REL_6',
 'P1SEX_1',
 'P1SEX_2',
 'P1AGE_1',
 'P1AGE_2',
 'P1AGE_3',
 'P1AGE_4',
 'P1AGE_5',
 'P2AGE_1',
 'P2AGE_2',
 'P2AGE_3',
 'P2AGE_4',
 'P2AGE_5',
 'P2REL_1',
 'P2REL_2',
 'P2REL_3',
 'P2REL_4',
 'P2REL_5',
 'P2REL_6',
 'P2SEX_1',
 'P2SEX_2',
 'P2MRSTA_1',
 'P2MRSTA_2',
 'P2MRSTA_3',
 'P2MRSTA_4',
 'P2MRSTA_5',
 'P2MRSTA_6',
 'P2MRSTA_7',
 'PAR1EMPL_1',
 'PAR1EMPL_2',
 'PAR1EMPL_3',
 'PAR1EMPL_4',
 'PAR1FTFY_1',
 'PAR1FTFY_2',
 'PAR1FTFY_3',
 'PAR2FTFY_1',
 'PAR2FTFY_2',
 'PAR2FTFY_3',
 'NUMSIBSX_0',
 'NUMSIBSX_1',
 'NUMSIBSX_2',
 'NUMSIBSX_3',
 'NUMSIBSX_4',
 'NUMSIBSX_5',
 'NUMSIBSX_6',
 'NUMSIBSX_7',
 'TTLHHINC_1',
 'TTLHHINC_2',
 'TTLHHINC_3',
 'TTLHHINC_4',
 'TTLHHINC_5',
 'TTLHHINC_6',
 'TTLHHINC_7',
 'TTLHHINC_8',
 'TTLHHINC_9',
 'TTLHHINC_10',
 'TTLHHINC_11',
 'TTLHHINC_12',
 'OWNRNTHB_1',
 'OWNRNTHB_2',
 'OWNRNTHB_3']

In [236]:
#Creating a correlation matrix
school_data_df.corr()

,Unnamed: 0,SEGRADES_0,SEGRADES_1,CENREG_1,CENREG_2,CENREG_3,CENREG_4,SCHRTSCHL_1,SCHRTSCHL_2,SEENJOY_1,...,TTLHHINC_6,TTLHHINC_7,TTLHHINC_8,TTLHHINC_9,TTLHHINC_10,TTLHHINC_11,TTLHHINC_12,OWNRNTHB_1,OWNRNTHB_2,OWNRNTHB_3
Unnamed: 0,1.000000,0.045855,-0.045855,-0.024158,-0.031333,0.002633,0.053824,-0.044527,0.044527,0.019731,...,0.031654,0.029167,0.014047,-0.039452,0.019562,-0.164217,-0.200671,-0.013734,0.008684,0.017572
SEGRADES_0,0.045855,1.000000,-1.000000,-0.002561,-0.004609,-0.021285,0.028067,0.008308,-0.008308,-0.253430,...,0.031715,0.017159,-0.014610,-0.061809,-0.086001,-0.045935,-0.070541,-0.085298,0.079925,0.025749
SEGRADES_1,-0.045855,-1.000000,1.000000,0.002561,0.004609,0.021285,-0.028067,-0.008308,0.008308,0.253430,...,-0.031715,-0.017159,0.014610,0.061809,0.086001,0.045935,0.070541,0.085298,-0.079925,-0.025749
CENREG_1,-0.024158,-0.002561,0.002561,1.000000,-0.342945,-0.237430,-0.251499,-0.030198,0.030198,0.002387,...,-0.018295,-0.017906,-0.007304,0.016382,0.073136,0.002532,0.028088,0.019517,-0.017951,-0.006972
CENREG_2,-0.031333,-0.004609,0.004609,-0.342945,1.000000,-0.409741,-0.434020,0.010886,-0.010886,-0.005914,...,0.003180,0.004223,-0.008657,-0.024155,-0.041257,-0.001231,-0.018414,0.002996,-0.004478,0.004457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTLHHINC_11,-0.164217,-0.045935,0.045935,0.002532,-0.001231,-0.010162,0.009042,-0.000882,0.000882,0.003016,...,-0.037958,-0.046079,-0.062688,-0.069701,-0.058346,1.000000,-0.024079,0.045015,-0.041188,-0.016771
TTLHHINC_12,-0.200671,-0.070541,0.070541,0.028088,-0.018414,-0.018328,0.014155,-0.017491,0.017491,0.012008,...,-0.046339,-0.056254,-0.076530,-0.085092,-0.071230,-0.024079,1.000000,0.069829,-0.066250,-0.018449
OWNRNTHB_1,-0.013734,-0.085298,0.085298,0.019517,0.002996,0.090036,-0.107634,-0.050148,0.050148,-0.037965,...,-0.031360,0.008676,0.074758,0.137188,0.140731,0.045015,0.069829,1.000000,-0.953351,-0.249460
OWNRNTHB_2,0.008684,0.079925,-0.079925,-0.017951,-0.004478,-0.091258,0.109132,0.047014,-0.047014,0.036282,...,0.027368,-0.007027,-0.068944,-0.127471,-0.132910,-0.041188,-0.066250,-0.953351,1.000000,-0.054498
OWNRNTHB_3,0.017572,0.025749,-0.025749,-0.006972,0.004457,-0.005065,0.005935,0.015058,-0.015058,0.009187,...,0.015939,-0.006155,-0.026113,-0.044865,-0.039138,-0.016771,-0.018449,-0.249460,-0.054498,1.000000

In [237]:
X = school_data_df.drop(columns = {'SEGRADES_0', 'Unnamed: 0','SEGRADES_1'}, axis=1)
y = school_data_df['SEGRADES_1']

In [238]:
#Random Forest
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [239]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [240]:
# Creating a StandardScaler instance.
#scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
#X_scaler = scaler.fit(X_train)

# Scaling the data.
#X_train_scaled = X_scaler.transform(X_train)
#X_test_scaled = X_scaler.transform(X_test)

In [241]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [242]:
# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

In [243]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)

In [244]:
# Calculating the confusion matrix.
#we analyze how well our random forest model classifies loan applications
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0         1429         1246
Actual 1          801         2819

In [245]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [246]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         1429         1246
Actual 1          801         2819

Accuracy Score : 0.6748212867355043
Classification Report
              precision    recall  f1-score   support

           0       0.64      0.53      0.58      2675
           1       0.69      0.78      0.73      3620

    accuracy                           0.67      6295
   macro avg       0.67      0.66      0.66      6295
weighted avg       0.67      0.67      0.67      6295

In [247]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.03059012668702888, 'SEENJOY_1'),
 (0.014386320125003743, 'FHHOME_4'),
 (0.014082085707087808, 'SEENJOY_2'),
 (0.01345315194413181, 'NUMSIBSX_1'),
 (0.013103972497077083, 'SEABSNT_1'),
 (0.01302741440227484, 'CENREG_2'),
 (0.012881682944611563, 'FODINNERX_3'),
 (0.0127325505594228, 'FODINNERX_4'),
 (0.012276802460343635, 'FOGROUPX_1'),
 (0.012257158174158697, 'FCTEACHR_1'),
 (0.012161086419868843, 'FOBUILDX_1'),
 (0.012041810163775578, 'FOGROUPX_2'),
 (0.012028996062992162, 'FOBUILDX_2'),
 (0.011826532581699615, 'FCSCHOOL_1'),
 (0.011755787486984446, 'FHHOME_3'),
 (0.011750103132794737, 'CENREG_4'),
 (0.011569596664894944, 'NUMSIBSX_0'),
 (0.011484130858203495, 'FOHISTX_1'),
 (0.011466158669208667, 'FOSTORY2X_1'),
 (0.011411388475720395, 'FOHISTX_2'),
 (0.011321055924964284, 'FOSTORY2X_2'),
 (0.01124729522376719, 'FODINNERX_2'),
 (0.011213944098429332, 'CENREG_3'),
 (0.011095540713322314, 'PAR2FTFY_1'),
 (0.01074342015905445, 'TTLHHINC_9'),
 (0.010630195956515792, 'FOCRAFTS_1'),
 (0.010470061296078218, 'NUMSIBSX_2'),
 (0.010442400898593154, 'FOCONCRTX_2'),
 (0.010351263536444829, 'FOGAMES_2'),
 (0.010332295512419718, 'PAR1FTFY_1'),
 (0.010277256534584897, 'TTLHHINC_8'),
 (0.010269247792343277, 'FOCRAFTS_2'),
 (0.010265884998005684, 'FOSPORT_2'),
 (0.010178010739946754, 'FOCONCRTX_1'),
 (0.010123392915389277, 'CENREG_1'),
 (0.01006081775770128, 'FOSPORT_1'),
 (0.01003769326639814, 'FOLIBRAYX_2'),
 (0.009969110626345978, 'FORESPON_1'),
 (0.009961146694464577, 'SEABSNT_2'),
 (0.009926838416165122, 'FOLIBRAYX_1'),
 (0.009926827225341018, 'FOGAMES_1'),
 (0.009881379217064645, 'FORESPON_2'),
 (0.009861341020708504, 'PAR1EMPL_1'),
 (0.009858185196667426, 'FCTEACHR_2'),
 (0.009784759927778846, 'PAR1FTFY_2'),
 (0.009755874333779307, 'P2REL_1'),
 (0.00974280638400216, 'PAR2FTFY_2'),
 (0.009734352192780517, 'P1AGE_3'),
 (0.009695652062798918, 'P2AGE_3'),
 (0.009622131465447582, 'FCSTDS_1'),
 (0.009601338369938048, 'SEENJOY_3'),
 (0.009387933782779146, 'FHHOME_2'),
 (0.009297923742564424, 'FOBOOKSTX_1'),
 (0.00928556579429233, 'FOBOOKSTX_2'),
 (0.009162860325425995, 'TTLHHINC_10'),
 (0.009107982409531132, 'P2SEX_2'),
 (0.009010222424913979, 'FCSTDS_2'),
 (0.008890797845441206, 'FOMUSEUMX_1'),
 (0.008832067476369514, 'P1AGE_2'),
 (0.008791929313659689, 'FOMUSEUMX_2'),
 (0.008772203411324685, 'P2AGE_2'),
 (0.008749058360439196, 'P2SEX_1'),
 (0.0086607592372361, 'P1SEX_1'),
 (0.00864654731084648, 'P1SEX_2'),
 (0.00833499242452805, 'SEABSNT_3'),
 (0.00806308542273094, 'FCSCHOOL_2'),
 (0.00802556503917016, 'OWNRNTHB_1'),
 (0.007994880903467293, 'SEABSNT_0'),
 (0.007932003210500608, 'PAR1EMPL_4'),
 (0.007816530026158217, 'FOZOOX_1'),
 (0.007691049222190749, 'TTLHHINC_7'),
 (0.007658180626673716, 'FOZOOX_2'),
 (0.007548887242056463, 'PAR1EMPL_2'),
 (0.0075015696892713, 'PAR2FTFY_3'),
 (0.0073766950072156855, 'OWNRNTHB_2'),
 (0.007123723434057432, 'PAR1FTFY_3'),
 (0.0067160701803733415, 'TTLHHINC_4'),
 (0.006510649390447755, 'P1REL_1'),
 (0.006391349810231567, 'TTLHHINC_5'),
 (0.006362505520710733, 'CSPEAKX_2'),
 (0.006199963729912915, 'P2MRSTA_1'),
 (0.006106208979708425, 'TTLHHINC_6'),
 (0.005972915472461092, 'SEABSNT_4'),
 (0.005895019653959029, 'TTLHHINC_3'),
 (0.0058040148162085145, 'HHENGLISH_1'),
 (0.0057895422361145836, 'SEABSNT_5'),
 (0.005762960388586643, 'P2REL_3'),
 (0.005541506814996524, 'HHENGLISH_2'),
 (0.00536749659380681, 'NUMSIBSX_3'),
 (0.005332275558902495, 'FHHOME_1'),
 (0.005289432418185166, 'SCHRTSCHL_2'),
 (0.005113441421813403, 'SCHRTSCHL_1'),
 (0.005037597015946988, 'TTLHHINC_2'),
 (0.004323511313355837, 'FODINNERX_1'),
 (0.004237869499004831, 'FCSTDS_3'),
 (0.004218876459721547, 'P2AGE_4'),
 (0.004134438625189482, 'FCTEACHR_3'),
 (0.0038813901507439106, 'FCSCHOOL_3'),
 (0.0035751276209248506, 'SEABSNT_6'),
 (0.0034687926983137966, 'CSPEAKX_5'),
 (0.0033991309409792166, 'CSPEAKX_3'),
 (0.003375393201669677, 'TTLHHINC_12'),
 (0.00323675205710686, 'SEABSNT_10'),
 (0.003232897338090548, 'P1AGE_4'),
 (0.003154653457169509, 'P2MRSTA_5'),
 (0.003061836773213896, 'P2REL_5'),
 (0.0030565760790996523, 'CSPEAKX_6'),
 (0.003000752430348792, 'FHWKHRS_1'),
 (0.0029109038212878687, 'PAR1EMPL_3'),
 (0.00290525651016649, 'P2MRSTA_3'),
 (0.0028970914262382162, 'FHWKHRS_2'),
 (0.002874180620945639, 'TTLHHINC_1'),
 (0.002773965677430143, 'TTLHHINC_11'),
 (0.0026656768761427474, 'CSPEAKX_4'),
 (0.002603524650494511, 'P1REL_3'),
 (0.002599678292469369, 'SEABSNT_7'),
 (0.0023637695091347152, 'SEABSNT_8'),
 (0.002244895834861235, 'P1REL_5'),
 (0.0021316310236894776, 'P1REL_2'),
 (0.002106641307768349, 'SEENJOY_4'),
 (0.0020506659692620995, 'P2REL_2'),
 (0.0018186918355149956, 'NUMSIBSX_4'),
 (0.0017887307481606535, 'FCTEACHR_4'),
 (0.0017488760935788106, 'P2REL_6'),
 (0.001715821982561437, 'FCSTDS_4'),
 (0.0015673013693131318, 'FCSCHOOL_4'),
 (0.0015011464358400868, 'OWNRNTHB_3'),
 (0.0012940888589334004, 'SEABSNT_9'),
 (0.0010163855892686053, 'SEABSNT_15'),
 (0.0008703685978576392, 'SEABSNT_12'),
 (0.0008020025526844023, 'P2MRSTA_7'),
 (0.0007647245699210609, 'P1REL_6'),
 (0.0007128532237926626, 'P2MRSTA_4'),
 (0.000660700458431732, 'SEABSNT_11'),
 (0.000594054717408587, 'SEABSNT_20'),
 (0.0005657853857865502, 'NUMSIBSX_5'),
 (0.0005615497934401693, 'P2MRSTA_2'),
 (0.0005373561464777731, 'SEABSNT_14'),
 (0.00034666190668446954, 'SEABSNT_13'),
 (0.0003378879668415744, 'P1REL_4'),
 (0.00032490096833357867, 'P2REL_4'),
 (0.0002600181337974194, 'P2MRSTA_6'),
 (0.00022630026329796733, 'SEABSNT_30'),
 (0.0002188611756291422, 'P2AGE_5'),
 (0.0002114753550577353, 'FHWKHRS_3'),
 (0.00016968265733038147, 'SEABSNT_16'),
 (0.00014615953322451547, 'CSPEAKX_1'),
 (0.00014573554779681843, 'NUMSIBSX_6'),
 (0.00014547918153111076, 'SEABSNT_17'),
 (0.00012343925005317173, 'SEABSNT_25'),
 (0.000100301165983004, 'FHWKHRS_4'),
 (8.024935781426078e-05, 'SEABSNT_18'),
 (7.546297582320684e-05, 'SEABSNT_27'),
 (7.533010086242827e-05, 'P1AGE_5'),
 (7.427602633466899e-05, 'SEABSNT_22'),
 (5.373530686326576e-05, 'SEABSNT_21'),
 (3.131744602712421e-05, 'SEABSNT_100'),
 (3.0380369458562482e-05, 'SEABSNT_19'),
 (2.342558656380998e-05, 'P2AGE_1'),
 (2.206435782535678e-05, 'P1AGE_1'),
 (2.0632202690291243e-05, 'SEABSNT_92'),
 (2.0136669852215063e-05, 'NUMSIBSX_7'),
 (1.9646668375613845e-05, 'SEABSNT_29'),
 (1.8284738295083536e-05, 'SEABSNT_43'),
 (1.722602585529367e-05, 'SEABSNT_167'),
 (1.5490477852953878e-05, 'SEABSNT_44'),
 (1.5340929252962314e-05, 'SEABSNT_60'),
 (1.314921294214489e-05, 'SEABSNT_34'),
 (1.2932244181966225e-05, 'SEABSNT_28'),
 (1.291529669063831e-05, 'SEABSNT_23'),
 (1.2423140448299176e-05, 'SEABSNT_33'),
 (1.18024021408747e-05, 'SEABSNT_40'),
 (1.1037702997258501e-05, 'SEABSNT_26'),
 (1.0031678835993793e-05, 'SEABSNT_50'),
 (8.252594358773214e-06, 'SEABSNT_65'),
 (7.531493919677398e-06, 'SEABSNT_75'),
 (4.9311284133166825e-06, 'SEABSNT_52'),
 (3.9247317251214676e-06, 'SEABSNT_37'),
 (2.940135681793804e-06, 'SEABSNT_90'),
 (2.811044241447723e-06, 'SEABSNT_72'),
 (2.5799362023479983e-06, 'SEABSNT_42'),
 (8.760510889989286e-07, 'SEABSNT_39'),
 (7.8182157044374e-07, 'SEABSNT_24'),
 (5.18355722318342e-07, 'SEABSNT_130'),
 (0.0, 'SEABSNT_80'),
 (0.0, 'SEABSNT_76'),
 (0.0, 'SEABSNT_63'),
 (0.0, 'SEABSNT_48'),
 (0.0, 'SEABSNT_45'),
 (0.0, 'SEABSNT_35')]

In [248]:
#print(importances)
Data= sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

#Creating a dataframe to filter by highest correlation and feature importance
feature_df=pd.DataFrame(Data,columns=["value","feature"])

#Trying to identify a number that will improve our outcome
feature_df=feature_df.loc[(feature_df["value"]>.005)]
feature_list= feature_df["feature"].tolist()


X = school_data_df[feature_list]
y = school_data_df['SEGRADES_1']

print(feature_list)

['SEENJOY_1', 'FHHOME_4', 'SEENJOY_2', 'NUMSIBSX_1', 'SEABSNT_1', 'CENREG_2', 'FODINNERX_3', 'FODINNERX_4', 'FOGROUPX_1', 'FCTEACHR_1', 'FOBUILDX_1', 'FOGROUPX_2', 'FOBUILDX_2', 'FCSCHOOL_1', 'FHHOME_3', 'CENREG_4', 'NUMSIBSX_0', 'FOHISTX_1', 'FOSTORY2X_1', 'FOHISTX_2', 'FOSTORY2X_2', 'FODINNERX_2', 'CENREG_3', 'PAR2FTFY_1', 'TTLHHINC_9', 'FOCRAFTS_1', 'NUMSIBSX_2', 'FOCONCRTX_2', 'FOGAMES_2', 'PAR1FTFY_1', 'TTLHHINC_8', 'FOCRAFTS_2', 'FOSPORT_2', 'FOCONCRTX_1', 'CENREG_1', 'FOSPORT_1', 'FOLIBRAYX_2', 'FORESPON_1', 'SEABSNT_2', 'FOLIBRAYX_1', 'FOGAMES_1', 'FORESPON_2', 'PAR1EMPL_1', 'FCTEACHR_2', 'PAR1FTFY_2', 'P2REL_1', 'PAR2FTFY_2', 'P1AGE_3', 'P2AGE_3', 'FCSTDS_1', 'SEENJOY_3', 'FHHOME_2', 'FOBOOKSTX_1', 'FOBOOKSTX_2', 'TTLHHINC_10', 'P2SEX_2', 'FCSTDS_2', 'FOMUSEUMX_1', 'P1AGE_2', 'FOMUSEUMX_2', 'P2AGE_2', 'P2SEX_1', 'P1SEX_1', 'P1SEX_2', 'SEABSNT_3', 'FCSCHOOL_2', 'OWNRNTHB_1', 'SEABSNT_0', 'PAR1EMPL_4', 'FOZOOX_1', 'TTLHHINC_7', 'FOZOOX_2', 'PAR1EMPL_2', 'PAR2FTFY_3', 'OWNRNTHB_2', 'PAR1FTFY_3', 'TTLHHINC_4', 'P1REL_1', 'TTLHHINC_5', 'CSPEAKX_2', 'P2MRSTA_1', 'TTLHHINC_6', 'SEABSNT_4', 'TTLHHINC_3', 'HHENGLISH_1', 'SEABSNT_5', 'P2REL_3', 'HHENGLISH_2', 'NUMSIBSX_3', 'FHHOME_1', 'SCHRTSCHL_2', 'SCHRTSCHL_1', 'TTLHHINC_2']

In [249]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [250]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
#X_scaler = scaler.fit(X_train)

# Scaling the data.
#X_train_scaled = X_scaler.transform(X_train)
#X_test_scaled = X_scaler.transform(X_test)

In [261]:
from sklearn.ensemble import GradientBoostingClassifier

learning_rates = [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1]

for learning_rate in learning_rates:
    classifier = GradientBoostingClassifier(n_estimators=20,
    learning_rate=learning_rate,
    max_features=12,
    max_depth=3,
    random_state=0)
    classifier.fit(X_train, y_train)
    print("Learning rate: ", learning_rate)
    print("Accuracy score (training): {0:.3f}".format(
           classifier.score(
               X_train,
               y_train)))
    print("Accuracy score (validation): {0:.3f}".format(
           classifier.score(
               X_test,
               y_test)))

Learning rate:  0.05
Accuracy score (training): 0.632
Accuracy score (validation): 0.632
Learning rate:  0.1
Accuracy score (training): 0.655
Accuracy score (validation): 0.660
Learning rate:  0.15
Accuracy score (training): 0.662
Accuracy score (validation): 0.667
Learning rate:  0.2
Accuracy score (training): 0.668
Accuracy score (validation): 0.669
Learning rate:  0.25
Accuracy score (training): 0.668
Accuracy score (validation): 0.670
Learning rate:  0.3
Accuracy score (training): 0.669
Accuracy score (validation): 0.668
Learning rate:  0.35
Accuracy score (training): 0.673
Accuracy score (validation): 0.668
Learning rate:  0.4
Accuracy score (training): 0.673
Accuracy score (validation): 0.670
Learning rate:  0.45
Accuracy score (training): 0.674
Accuracy score (validation): 0.672
Learning rate:  0.5
Accuracy score (training): 0.675
Accuracy score (validation): 0.674
Learning rate:  0.55
Accuracy score (training): 0.676
Accuracy score (validation): 0.670
Learning rate:  0.6
Accuracy score (training): 0.676
Accuracy score (validation): 0.671
Learning rate:  0.65
Accuracy score (training): 0.678
Accuracy score (validation): 0.668
Learning rate:  0.7
Accuracy score (training): 0.676
Accuracy score (validation): 0.675
Learning rate:  0.75
Accuracy score (training): 0.675
Accuracy score (validation): 0.669
Learning rate:  0.8
Accuracy score (training): 0.676
Accuracy score (validation): 0.671
Learning rate:  0.85
Accuracy score (training): 0.673
Accuracy score (validation): 0.668
Learning rate:  0.9
Accuracy score (training): 0.677
Accuracy score (validation): 0.665
Learning rate:  0.95
Accuracy score (training): 0.675
Accuracy score (validation): 0.671
Learning rate:  1
Accuracy score (training): 0.676
Accuracy score (validation): 0.671

In [262]:
# Choose a learning rate and create classifier
classifier = GradientBoostingClassifier(n_estimators=20,
                                        learning_rate=.65,
                                        max_features=10,
                                        max_depth=3,
                                        random_state=0)

# Fit the model
classifier.fit(X_train, y_train)

# Make Prediction
predictions = classifier.predict(X_test)
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).head(20)

       Prediction  Actual
23974           0       1
10511           0       0
16391           1       1
4174            0       0
5009            0       1
2603            1       0
8460            0       1
23093           0       0
10078           1       1
24933           0       0
11481           0       0
743             0       0
21431           0       1
5717            1       1
14220           0       0
1015            1       1
19168           0       1
10393           0       1
10757           1       0
1803            0       0

In [263]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.6705321683876092

In [264]:
# Generate the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"],
    columns=["Predicted 0", "Predicted 1"]
)

# Displaying results
display(cm_df)

          Predicted 0  Predicted 1
Actual 0         1421         1254
Actual 1          820         2800

In [265]:
# Fitting the model
rf_model = rf_model.fit(X_train, y_train)

In [266]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test)

In [267]:
# Calculating the confusion matrix.
#we analyze how well our random forest model classifies loan applications
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0         1450         1225
Actual 1          851         2769

In [268]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

In [269]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         1450         1225
Actual 1          851         2769

Accuracy Score : 0.6702144559173947
Classification Report
              precision    recall  f1-score   support

           0       0.63      0.54      0.58      2675
           1       0.69      0.76      0.73      3620

    accuracy                           0.67      6295
   macro avg       0.66      0.65      0.66      6295
weighted avg       0.67      0.67      0.67      6295

In [270]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
# We can sort the features by their importance.
#sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)